fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    systemd: "git://github.com/SaltaIT/eyp-systemd.git"
    eyplib: "git://github.com/SaltaIT/eyp-eyplib.git"
  symlinks:
    prometheus: "#{source_dir}"
